<a href="https://colab.research.google.com/github/MAB1144-Python/DS_Brayan_Andru/blob/main/tercera.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import numpy as np

In [ ]:
A = np.array([1,2,3,4,5,6])
B = [1,2,3,4,5,6]

In [ ]:
A

array([1, 2, 3, 4, 5, 6])

In [ ]:
B

[1, 2, 3, 4, 5, 6]

In [ ]:
A + B

In [ ]:
A = np.array([[1,2,3,4,5,6],[9,8,7,5,6,5],[9,8,7,5,6,5],[9,8,7,5,6,5],[9,8,7,5,6,5],[9,8,7,5,6,5]])
A

array([[1, 2, 3, 4, 5, 6],
       [9, 8, 7, 5, 6, 5],
       [9, 8, 7, 5, 6, 5],
       [9, 8, 7, 5, 6, 5],
       [9, 8, 7, 5, 6, 5],
       [9, 8, 7, 5, 6, 5]])

In [ ]:
A[5,5] = 44
A

array([[ 1,  2,  3,  4,  5,  6],
       [ 9,  8,  7,  5,  6,  5],
       [ 9,  8,  7,  5,  6,  5],
       [ 9,  8,  7,  5,  6,  5],
       [ 9,  8,  7,  5,  6,  5],
       [ 9,  8,  7,  5,  6, 44]])

In [ ]:
A[2] = [58,57,62,54,22,33]
A

array([[ 1,  2,  3,  4,  5,  6],
       [ 9,  8,  7,  5,  6,  5],
       [58, 57, 62, 54, 22, 33],
       [ 9,  8,  7,  5,  6,  5],
       [ 9,  8,  7,  5,  6,  5],
       [ 9,  8,  7,  5,  6, 44]])

In [ ]:
A[2:]

array([[58, 57, 62, 54, 22, 33],
       [ 9,  8,  7,  5,  6,  5],
       [ 9,  8,  7,  5,  6,  5],
       [ 9,  8,  7,  5,  6, 44]])

In [ ]:
A

array([[ 1,  2,  3,  4,  5,  6],
       [ 9,  8,  7,  5,  6,  5],
       [58, 57, 62, 54, 22, 33],
       [ 9,  8,  7,  5,  6,  5],
       [ 9,  8,  7,  5,  6,  5],
       [ 9,  8,  7,  5,  6, 44]])

In [ ]:
A[:2,2:4]

array([[3, 4],
       [7, 5]])

In [ ]:
m1 = np.array([[1  ,2  ,3  ,4  ,5 ],
               [6  ,7  ,8  ,9  ,10],
               [11 ,12 ,13 ,14 ,15],
               [16 ,17 ,18 ,19 ,20],
               [21 ,22 ,23 ,24 ,25]])

In [ ]:
m1[1:3,3:5]

array([[ 9, 10],
       [14, 15]])

In [ ]:
m1[:3,:3]=[[41,42,43],
           [46,47,48],
           [51,52,53]]
m1

array([[ 41,  42,  43,   4,   5],
       [ 46,  47,  48,   9,  10],
       [ 51,  52,  53,  14,  15],
       [ 16,  17,  18, 195,  20],
       [ 21,  22,  23,  24,  25]])

In [ ]:
m1 = np.array([[1  ,2  ,3  ,4  ,5 ],
               [6  ,7  ,8  ,9  ,10],
               [11 ,12 ,13 ,14 ,15],
               [16 ,17 ,18 ,19 ,20],
               [21 ,22 ,23 ,24 ,25]])

In [ ]:
dic = {'camilo':26,'david':30,'Esteban':25,'Laura':{'edad':23,'lugar':'cucuta','pet':'gatos'}}
dic

{'camilo': 26,
 'david': 30,
 'Esteban': 25,
 'Laura': {'edad': 23, 'lugar': 'cucuta', 'pet': 'gatos'}}

In [ ]:
dic['jose']=[24,'bogota']

In [ ]:
dic.keys()

dict_keys(['camilo', 'david', 'Esteban', 'Laura', 'jose'])

In [ ]:
ced = [123,456,789]
nom = ['camilo', 'david', 'Esteban']
eda = [26,25,24]
per = {}
for i in range(len(ced)):
  per[ced[i]] = {'nombre':nom[i],'edad':eda[i]}
  print(ced[i],nom[i],eda[i])
per

123 camilo 26
456 david 25
789 Esteban 24


{123: {'nombre': 'camilo', 'edad': 26},
 456: {'nombre': 'david', 'edad': 25},
 789: {'nombre': 'Esteban', 'edad': 24}}

In [ ]:
cliente = '''Americas
Americas
Americas
Americas
Americas
Americas
Americas
Americas
Americas
Americas
Americas
Americas
Americas
Avidanti
Avidanti
Avidanti
Avidanti
Avidanti
Avidanti
Avidanti
BSC
BSC
BSC
BSC
BSC
BSC
BSC
BSC
BSC
BSC
BSC
BSC
BSC
BSC
BSC
BSC
BSC
BSC
BSC'''

In [ ]:
cliente = cliente.split('\n')

'Americas\nAmericas\nAmericas\nAmericas\nAmericas\nAmericas\nAmericas\nAmericas\nAmericas\nAmericas\nAmericas\nAmericas\nAmericas\nAvidanti\nAvidanti\nAvidanti\nAvidanti\nAvidanti\nAvidanti\nAvidanti\nBSC\nBSC\nBSC\nBSC\nBSC\nBSC\nBSC\nBSC\nBSC\nBSC\nBSC\nBSC\nBSC\nBSC\nBSC\nBSC\nBSC\nBSC\nBSC'

In [ ]:
USER = '''jgcendales@lasamericas.com.co
caro.toroco@gmail.com
clavijoabsalon@gmail.com
willyhands@hotmail.com
ivanoas@hotmail.com
coorurgencias@correo1lasamericas.com
uci.uce@lasamericas.com.co
ucimurillo@yahoo.com
bladigil@yahoo.com
metrologia.lasamericas@gmail.com
angelica.carmona@lasamericas.com.co
jose.mieles@lasamericas.com.co
pmla@lasamericas.com
sandra.pena@avidanti.com
marioarcia@hotmail.com
diefer8@hotmail.com
alvaroleal17feb@gmail.com
ceye_urgencias@avidanti.com
ceye_hospital@avidanti.com
ceye_uci@avidanti.com
julian.ballesteros@bsci.com
carlos.molina@bsci.com
andres.sanchezavendano@bsci.com
clinicaleye1@bsci.com
sandra.amayacastellanos@bsci.com
sandra.barajas@bsci.com
carolina.suarez@bsci.com
john.castellanos@bsci.com
sonia.corredor@bsci.com
Vanessa.VelasquezCorrea@bsci.com
viviana.escobar@bsci.com
duberney.henao@bsci.com
juliana.jaramilloescobar@bsci.com
alejandra.moralesvelez@bsci.com
ana.ospinaospina@bsci.com
angela.uribe@bsci.com
fernando.ruiz@bsci.com
johnnatan.giraldo@bsci.com
zulma.galeanoaguilar@bsci.com
diego.gutierrezmoran@bsci.com
gustavo.betancourt@bsci.com
jefferson.vanegasrueda@bsci.com
fabio.escorciapena@bsci.com
mauricio.fernandez@bsci.com
miguel.sanjuan@bsci.com
jackeline.vegamedina@bsci.com
jesus.mayagallego@bsci.com
natalia.gallegoduque@bsci.com
xiomara.cuervo@bsci.com
paula.ovalle@bsci.com
liliapatricia.roldanduarte@bsci.com
linda.delacruzgomez@bsci.com
dany.ballestas@bsci.com
andrea.morales@bsci.com
harold.quinteromarin@bsci.com
victor.valenzuelajara@bsci.com
catalina.lopezgutierrez@bsci.com
tania.jimenez@bsci.com'''

In [ ]:
PASSWORD = '''Jgcendales
Ctoroamericas
Aclavijo
Wmayaamericas
Dsilvaamericas
Jlopezamericas
Gafasamericas
Rmurillo
Bgilamericas
Metrologia2020
Acarmona2020
Jmieles2020
Americas2020
Spena2020
Marcia2020
Dacosta2020
Aleal2020
Urgencias2020
Hospital2020
Uciavidanti2020
Boston2020
Boston2020
Boston2020
Clinic@leye1
Samaya2020
Sbarajas2020
Csuarez2020
Jcastellanos
Scorredor
Vvelasquez
Vescobar
Dhenao2020
Jjaramillo
Amorales
Aospina2020
Auribe202
Fruiz2020
Jgiraldo
Zgaleano
Dgutierrez
Gbetancourt
Jvanegas
Fescorcia
Mfernandez
Msanjuan'''

In [ ]:
USER_ID='''888256100497098
770703541478868
503689939669216
456377306776449
479046292979181
649462302082354
892823815922478
30041315717374
832816381201192
217126523319734
874162594637022
206777226813820
167392339945581
170323652018158
794657932405988
775752684724657
735190945695722
314596971521233
847635489777796
567603732052368
369159428319974
181232986327638
975552749040084
424750220395261
923833106873600
527594621478092
617774317988953
556676416561222
218114994953908
54432319583274
68790901241445
689658739700816
468613107696000
271879578584911
169848697408172
756363201949599
99859666459959
139552871061260
768980109157828
725607152439564
61731381275250
713193116255361
879985530893759
673557915348196
117668954981525
268321498224407
747148118642791
821188677665668
477512665890651
622531697736436
860873151111173
973155445580405
370761967312305
440339166228735
373105841139739
593393773723349
462190503871159
199510548986656
106159694421499
418411520637954
8556354885275
151785717861445
155629809420367
87056775783677
747175321171770
4417024479387
535098491909312
341655297278817
216955052434508
956813772376803'''

In [ ]:
#dic_clientes={user:{zona:cliente,password:password,user_id:user_id}}
dic_clientes={}
for i in range(len(cliente)):
  

In [ ]:
from google.colab import drive
drive.mount('/content/drive')

Drive already mounted at /content/drive; to attempt to forcibly remount, call drive.mount("/content/drive", force_remount=True).


In [ ]:
ruta = '/content/drive/MyDrive/Colab Notebooks/dataset/clase19septiembre.csv'

In [ ]:
import pandas as pd
dataframe_1 = pd.read_csv(ruta)

In [ ]:
dataframe_1

school sex  age address famsize Pstatus  Medu  Fedu      Mjob      Fjob  \
0       GP   F   18       U     GT3       A     4     4   at_home   teacher   
1       GP   F   17       U     GT3       T     1     1   at_home     other   
2       GP   F   15       U     LE3       T     1     1   at_home     other   
3       GP   F   15       U     GT3       T     4     2    health  services   
4       GP   F   16       U     GT3       T     3     3     other     other   
..     ...  ..  ...     ...     ...     ...   ...   ...       ...       ...   
390     MS   M   20       U     LE3       A     2     2  services  services   
391     MS   M   17       U     LE3       T     3     1  services  services   
392     MS   M   21       R     GT3       T     1     1     other     other   
393     MS   M   18       R     LE3       T     3     2  services     other   
394     MS   M   19       U     LE3       T     1     1     other   at_home   

     ... famrel freetime  goout  Dalc  Walc health absences  G1  G2  G3  
0    ...      4        3      4     1     1      3        6   5   6   6  
1    ...      5        3      3     1     1      3        4   5   5   6  
2    ...      4        3      2     2     3      3       10   7   8  10  
3    ...      3        2      2     1     1      5        2  15  14  15  
4    ...      4        3      2     1     2      5        4   6  10  10  
..   ...    ...      ...    ...   ...   ...    ...      ...  ..  ..  ..  
390  ...      5        5      4     4     5      4       11   9   9   9  
391  ...      2        4      5     3     4      2        3  14  16  16  
392  ...      5        5      3     3     3      3        3  10   8   7  
393  ...      4        4      1     3     4      5        0  11  12  10  
394  ...      3        2      3     3     3      5        5   8   9   9  

[395 rows x 33 columns]

In [ ]:
dataframe_1.keys()

Index(['school', 'sex', 'age', 'address', 'famsize', 'Pstatus', 'Medu', 'Fedu',
       'Mjob', 'Fjob', 'reason', 'guardian', 'traveltime', 'studytime',
       'failures', 'schoolsup', 'famsup', 'paid', 'activities', 'nursery',
       'higher', 'internet', 'romantic', 'famrel', 'freetime', 'goout', 'Dalc',
       'Walc', 'health', 'absences', 'G1', 'G2', 'G3'],
      dtype='object')

In [ ]:
dataframe_1['Fjob']


0       teacher
1         other
2         other
3      services
4         other
         ...   
390    services
391    services
392       other
393       other
394     at_home
Name: Fjob, Length: 395, dtype: object

In [ ]:
data_1 = np.array(dataframe_1[['school', 'sex', 'age', 'address']])[:10]
data_1

array([['GP', 'F', 18, 'U'],
       ['GP', 'F', 17, 'U'],
       ['GP', 'F', 15, 'U'],
       ['GP', 'F', 15, 'U'],
       ['GP', 'F', 16, 'U'],
       ['GP', 'M', 16, 'U'],
       ['GP', 'M', 16, 'U'],
       ['GP', 'F', 17, 'U'],
       ['GP', 'M', 15, 'U'],
       ['GP', 'M', 15, 'U']], dtype=object)

In [ ]:
import random
class niño:
  def __init__(self,nombre,sexo,papa,mama):
    self.nombre = nombre
    self.sexo = sexo
    self.papa = papa
    self.mama = mama
    self.id = self.id()

  def id(self):
    num = 0
    while len(str(num))<2:
       num = int(random.random()*100)
       print(num)
    return num
  
  def prt(self):
    rt = self.nombre+' '+self.sexo+' '+self.papa+' '+self.mama
    return rt  



In [ ]:
class pais():
  def __init__(self,nombre):
    self.nombre = nombre
    self.ciud = []

  def new_p(self,nombre,sexo,papa,mama):
    band = True
    while band:
      ni = niño(nombre,sexo,papa,mama)
      band = self.verif(ni)
    self.ciud.append(ni)  

  def verif(self, ni_v):
    for cd in self.ciud:
      if ni_v.id == cd.id:
        return True
    return False


clb = pais('Colombia')

In [121]:
persona_1 = niño('Juan','M','Cesar','Ana')
print(clb.nombre)
print(clb.ciud)
clb.new_p('Juan','M','Cesar','Ana')
for cd in clb.ciud:
  print(cd.nombre,cd.id)


Se truncaron las últimas líneas 5000 del resultado de transmisión.
52
59
75
22
37
0
73
26
33
75
46
66
68
2
56
31
31
97
45
2
67
61
46
82
72
35
40
56
97
57
24
97
19
18
45
32
56
81
77
59
17
5
51
43
32
78
26
4
36
34
75
82
86
65
8
5
54
38
10
77
95
92
38
66
95
10
46
26
36
74
23
33
81
32
81
42
73
1
52
80
22
39
89
34
20
51
49
44
62
44
3
4
12
46
26
78
31
80
11
29
58
35
44
49
11
29
62
11
80
51
12
6
60
29
46
25
92
39
61
71
28
79
35
54
76
73
64
25
65
34
16
77
10
34
74
49
29
88
82
85
64
66
53
10
89
77
50
47
1
62
32
96
44
42
69
63
42
88
96
24
39
81
57
70
12
32
6
0
39
17
76
52
59
27
42
70
57
63
38
90
79
49
80
22
71
0
82
48
12
3
19
3
27
96
29
15
94
5
87
0
22
76
83
78
81
81
24
23
73
26
47
73
1
47
1
28
13
58
59
86
99
6
99
7
73
85
38
59
60
18
71
55
38
76
3
80
71
7
42
6
10
94
71
54
19
40
13
99
65
58
92
71
34
71
94
61
39
41
52
26
92
97
41
63
97
96
6
32
57
26
13
78
18
91
42
64
81
92
12
24
55
81
30
88
43
31
3
80
79
44
30
97
37
40
75
18
5
11
85
38
11
11
93
16
79
18
72
70
48
15
67
29
34
12
79
86
68
53
91
4
64


KeyboardInterrupt: ignored

In [122]:
ven = pais('Vene')